theme = "starlight"

[editor]
true-color = true
line-number = "relative"
rulers = [80]
shell = ["zsh", "-c"]
bufferline = "always"
rainbow-brackets = true

[editor.cursor-shape]
insert = "bar"

[editor.file-picker]
hidden = false

[keys.normal]
"tab" = ":buffer-next"
"S-tab" = ":buffer-previous"
esc = ["collapse_selection", "keep_primary_selection"]
C-f = [":new", ":insert-output lf -selection-path=/dev/stdout", "split_selection_on_newline", "goto_file", "goto_last_modification", "goto_last_modified_file", ":buffer-close!", ":redraw"]

# make sure there is only one selection, select word under cursor, set search to selection, then switch to select mode
"C-d" = ["keep_primary_selection", "move_prev_word_start", "move_next_word_end", "search_selection", "select_mode"]

[keys.insert]
C-space = "completion"

[keys.normal."space"]
x = ":buffer-close"

[keys.select]
# if already in select mode, just add new selection at next occurrence
"C-d" = ["search_selection", "extend_search_next"]
